name: 📊 Dataset Analysis Request
description: Request data analysis for a provided dataset
title: "[Analysis Request]: "

body:
  - type: markdown
    attributes:
      value: |
        Thank you for requesting data analysis on a dataset. Please provide the following information to help us understand your analysis needs. Your contribution to this project is appreciated!
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: A clear and concise description of the dataset and the analysis you need.
      placeholder: Describe the dataset and your analysis requirements in detail.
      value: "Describe the dataset and analysis requirements here"
    validations:
      required: true
  - type: textarea
    id: dataset
    attributes:
      label: 📊 Dataset Details
      description: Provide details about the dataset, including its source, format, and any relevant information.
      placeholder: Describe the dataset (e.g., source, format, size).
      value: "Dataset details here"
    validations:
      required: true
  - type: dropdown
    id: analysis_type
    attributes:
      label: 📈 Analysis Type
      description: Select the type of analysis you require.
      multiple: true
      options:
        - HacktoberFest
        - Descriptive Statistics
        - Data Visualization
        - Machine Learning
        - Other (please specify in the description)
    validations:
      required: true
  - type: textarea
    id: dataset_files
    attributes:
      label: 📂 Upload Dataset Files
      description: Please upload the dataset file(s) here. If you have multiple files, consider compressing them into a ZIP archive you can drag and down file here.
    validations:
      required: true
  - type: textarea
    id: deadline
    attributes:
      label: ⏰ Deadline (if applicable)
      description: Specify the deadline for this analysis request (if applicable).
      placeholder: Enter the deadline in YYYY-MM-DD format.
  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: I agree to and respect the Code of Conduct
      description: By submitting this request, you agree to follow our [CODE OF CONDUCT](https://github.com/rajatnai49/demo/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I will also follow [CONTRIBUTING GUIDELINES](https://github.com/rajatnai49/demo/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
          required: true
