name: 📃 Documentation issue report
description: Report an issue in the project's documentation
title: "[Documentation Bug]: "

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue in the project's documentation. Please fill out the following information to help us resolve the issue as quickly as possible.
        Thank you for taking time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: A clear and concise description of what the bug is.
      placeholder: Please describe the issue in detail.
      value: "Describe your bug here"
    validations:
      required: true
  - type: textarea
    id: instruction
    attributes:
      label: 🪃 Instructions to reproduce the issue
      description: Please provide a step-by-step instruction to reproduce the issue.
      placeholder: Please provide a step-by-step instruction to reproduce the issue.
      value: "Steps to reproduce the issue"
    validations:
      required: true
  - type: dropdown
    id: contribution
    attributes:
      label: Select the program in which you are contributing
      multiple: true
      options:
        - HacktoberFest
        - Critical
        - Minor
        - Other
    validations:
      required:
        type: array
        min: 1
  - type: checkboxes
    id: terms
    attributes:
      label: I agree to and respect the Code of Conduct
      description: By submitting this issue, you are agreeing to follow our [CODE OF CONDUCT](https://github.com/rajatnai49/demo/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I will follow [CONTRIBUTING GUIDELINES](https://github.com/rajatnai49/demo/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
          required: true
