name: 💫 Enhancement Request
description: Suggest an enhancement for the project
title: "[Enhancement]: "

body:
  - type: checkboxes
    attributes:
      value: |
        ** Before you submit the enhancement request, please ensure you have checked the following: **
        - [ ] I have searched for similar enhancement requests in the project's repository.
        - [ ] I have checked the project's documentation and resources for troubleshooting.

        Thank you for suggesting an enhancement to the project. Please fill out the following information to help us resolve the issue as quickly as possible.
        Thank you for taking time to fill out this enhancement request!
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: A clear and concise description of what the enhancement is.
      placeholder: Please describe the enhancement in detail.
      value: "Describe your enhancement here"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: 🎯 Motivation
      description: A clear and concise description of what the motivation for the enhancement is.
      placeholder: Please describe the motivation for the enhancement in detail.
      value: "Describe the motivation for the enhancement here"
    validations:
      required: true
  - type: dropdown
    id: labels
    attributes:
      label: Select the labels that best describe this enhancement.
      multiple: true
      options:
        - HacktoberFest
        - enhancement
        - Other
    validations:
      required: true
